# Generated by Django 5.2.1 on 2025-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='instafeeds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
